# Generated by Django 5.0.4 on 2024-05-10 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fonction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Quartier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('delimitation', models.TextField(verbose_name='Limitations du quartier')),
            ],
        ),
        migrations.CreateModel(
            name='Menbres',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('postnom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=255)),
                ('Adresse', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(max_length=255)),
                ('statut', models.CharField(choices=[('A', 'Ancien'), ('N', 'Nouveau'), ('O', 'Autre')], max_length=255)),
                ('etat_civil', models.CharField(choices=[('C', 'Célibataire'), ('M', 'Marié(e)'), ('D', 'Divorcé(e)'), ('V', 'Veuf/Veuve')], max_length=255)),
                ('photo', models.ImageField(blank=True, upload_to='images')),
                ('groupe_sanguin', models.CharField(max_length=255)),
                ('fonction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_menbres.fonction')),
                ('quartier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_menbres.quartier')),
            ],
            options={
                'verbose_name': 'Menbre',
                'verbose_name_plural': 'Menbres',
            },
        ),
        migrations.CreateModel(
            name='Gardinage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('heure_arrive', models.TimeField(verbose_name="Heure d'arrivée")),
                ('heure_depart', models.TimeField(verbose_name='Heure de départ')),
                ('remarque', models.TextField(verbose_name='Remarques')),
                ('garde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Garde', to='Gestion_menbres.menbres')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_menbres.menbres', verbose_name='Menbre')),
            ],
        ),
        migrations.CreateModel(
            name='Garde',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('profession', models.CharField(max_length=255, verbose_name='Profession')),
                ('statut', models.CharField(choices=[('A', 'Ancien'), ('N', 'Nouveau'), ('O', 'Autre')], max_length=255)),
                ('grade', models.CharField(choices=[('secretaire', 'Secrétaire'), ('disciplinaire', 'Disciplinaire'), ('commandant', 'Commandant')], max_length=255, verbose_name='Grade')),
                ('date_recrutement', models.DateField(verbose_name='Date de récrutement')),
                ('id_menbre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_menbres.menbres', verbose_name='Menbre')),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_even', models.CharField(max_length=255, verbose_name="Type d'événement")),
                ('date_even', models.DateField(verbose_name='Date')),
                ('place_even', models.CharField(max_length=255, verbose_name='Place')),
                ('membres', models.ManyToManyField(related_name='Evenement_membres', to='Gestion_menbres.menbres')),
            ],
        ),
        migrations.CreateModel(
            name='Diacre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('profession', models.CharField(max_length=255, verbose_name='Profession')),
                ('debut_mandat', models.DateField(verbose_name='Début mandat')),
                ('fin_mandat', models.DateField(verbose_name='Fin mandat')),
                ('etat_mandat', models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé'), ('suspendu', 'Suspendu'), ('autre', 'Autre')], max_length=255)),
                ('id_menbre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_menbres.menbres', verbose_name='Menbre')),
            ],
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_comm', models.CharField(max_length=255)),
                ('contenu', models.TextField()),
                ('date_comm', models.DateField()),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_menbres.menbres')),
            ],
        ),
        migrations.CreateModel(
            name='Administateur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('profession', models.CharField(max_length=255, verbose_name='Profession')),
                ('debut_mandat', models.DateField(verbose_name='Debut mandat')),
                ('fin_mandat', models.DateField(verbose_name='Fin mandat')),
                ('etat_mandat', models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé'), ('suspendu', 'Suspendu'), ('autre', 'Autre')], max_length=255, verbose_name='Etat mandat')),
                ('id_menbre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_menbres.menbres', verbose_name='Menbre')),
            ],
        ),
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_activ', models.CharField(max_length=255, verbose_name="Type d'activité")),
                ('date_activ', models.DateField(verbose_name='Date')),
                ('place_activ', models.CharField(max_length=255, verbose_name='Place')),
                ('membres', models.ManyToManyField(related_name='Activite_membres', to='Gestion_menbres.menbres')),
            ],
        ),
        migrations.CreateModel(
            name='Offrande',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_off', models.CharField(max_length=255, verbose_name="Type d'offrande")),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('date_off', models.DateField(verbose_name='Date')),
                ('menbre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_menbres.menbres')),
            ],
        ),
        migrations.CreateModel(
            name='Pasteur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fonction', models.CharField(choices=[('P', 'Principal'), ('A', 'Associé')], max_length=255)),
                ('id_menbre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_menbres.menbres', verbose_name='Menbre')),
            ],
        ),
        migrations.CreateModel(
            name='Comite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonction', models.CharField(max_length=255)),
                ('menbre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_menbres.menbres')),
                ('quartier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_menbres.quartier')),
            ],
        ),
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('departement', models.CharField(max_length=255, verbose_name='Département')),
                ('id_menbre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_menbres.menbres', verbose_name='Menbre')),
            ],
        ),
        migrations.CreateModel(
            name='Besoin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('materiel', models.TextField(verbose_name='Démande')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(verbose_name='Prix')),
                ('destinateur', models.CharField(max_length=255, verbose_name='Destinataire')),
                ('technicien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_menbres.technique', verbose_name='Téchnicien')),
            ],
        ),
    ]
