# Generated by Django 4.2.7 on 2024-08-07 11:03

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fonction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
            ],
        ),
        migrations.CreateModel(
            name='JourSemaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi'), ('dimanche', 'Dimanche')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Menbres',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('postnom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('genre', models.CharField(choices=[('Masculin', 'Masculin'), ('Féminin', 'Féminin')], max_length=255)),
                ('Adresse', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(max_length=255)),
                ('statut', models.CharField(choices=[('Actif', 'Actif'), ('Inactif', 'Inactif')], max_length=255, verbose_name='Statut')),
                ('etat_civil', models.CharField(choices=[('Célibataire', 'Célibataire'), ('Marié(e)', 'Marié(e)'), ('Divorcé(e)', 'Divorcé(e)'), ('Veuf/Veuve', 'Veuf/Veuve')], max_length=255, verbose_name='Etat civil')),
                ('photo', models.ImageField(blank=True, upload_to='images')),
                ('groupe_sanguin', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=255, verbose_name='Groupe sanguin')),
                ('fonction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_menbres.fonction')),
            ],
            options={
                'verbose_name': 'Menbre',
                'verbose_name_plural': 'Membres',
            },
        ),
        migrations.CreateModel(
            name='Quartier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('delimitation', models.TextField(verbose_name='Limitations du quartier')),
            ],
        ),
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('departement', models.CharField(max_length=255, verbose_name='Département')),
                ('id_menbre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_menbres.menbres', verbose_name='Menbre')),
            ],
        ),
        migrations.CreateModel(
            name='Pasteur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fonction', models.CharField(choices=[('P', 'Principal'), ('A', 'Associé')], max_length=255)),
                ('id_menbre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_menbres.menbres', verbose_name='Menbre')),
            ],
        ),
        migrations.CreateModel(
            name='Offrande',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_off', models.CharField(max_length=255, verbose_name="Type d'offrande")),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('date_off', models.DateField(verbose_name='Date')),
                ('menbre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_menbres.menbres')),
            ],
        ),
        migrations.AddField(
            model_name='menbres',
            name='quartier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_menbres.quartier', verbose_name='Quartier'),
        ),
        migrations.CreateModel(
            name='Gardinage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('heure_arrive', models.TimeField(verbose_name="Heure d'arrivée")),
                ('heure_depart', models.TimeField(verbose_name='Heure de départ')),
                ('remarque', models.TextField(verbose_name='Remarques')),
                ('garde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Garde', to='Gestion_menbres.menbres')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_menbres.menbres', verbose_name='Menbre')),
            ],
        ),
        migrations.CreateModel(
            name='Garde',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('profession', models.CharField(max_length=255, verbose_name='Profession')),
                ('statut', models.CharField(choices=[('A', 'Ancien'), ('N', 'Nouveau'), ('O', 'Autre')], max_length=255)),
                ('grade', models.CharField(choices=[('secretaire', 'Secrétaire'), ('disciplinaire', 'Disciplinaire'), ('commandant', 'Commandant')], max_length=255, verbose_name='Grade')),
                ('date_recrutement', models.DateField(verbose_name='Date de récrutement')),
                ('emploi_temps', models.ManyToManyField(to='Gestion_menbres.joursemaine', verbose_name='Emploi du temps')),
                ('id_menbre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_menbres.menbres', verbose_name='Menbre')),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_even', models.CharField(max_length=255, verbose_name="Type d'événement")),
                ('date_even', models.DateField(verbose_name='Date')),
                ('heure_even', models.TimeField(verbose_name='Heure')),
                ('place_even', models.CharField(max_length=255, verbose_name='Lieu')),
                ('autres', models.TextField(blank=True)),
                ('membres', models.ManyToManyField(blank=True, related_name='Evenement_membres', to='Gestion_menbres.menbres')),
            ],
        ),
        migrations.CreateModel(
            name='Diacre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('profession', models.CharField(max_length=255, verbose_name='Profession')),
                ('debut_mandat', models.DateField(verbose_name='Début mandat')),
                ('fin_mandat', models.DateField(verbose_name='Fin mandat')),
                ('etat_mandat', models.CharField(choices=[('En cour', 'En cours'), ('Terminé', 'Terminé'), ('Annulé', 'Annulé'), ('Suspendu', 'Suspendu'), ('Autre', 'Autre')], max_length=255)),
                ('id_menbre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_menbres.menbres', verbose_name='Menbre')),
            ],
        ),
        migrations.CreateModel(
            name='Culte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('heure_debut', models.TimeField(verbose_name='Debut service')),
                ('heure_fin', models.TimeField(verbose_name='Fin service')),
                ('predicateur_visiteur', models.CharField(blank=True, max_length=100, null=True, verbose_name='Prédicateur visiteur')),
                ('nombre_membres', models.PositiveIntegerField(blank=True, default=0, verbose_name='Effectif Total')),
                ('nombre_offrandes', models.FloatField(blank=True, default=0.0, verbose_name='Offrande Régulière')),
                ('nombre_construction', models.FloatField(blank=True, default=0.0, verbose_name='Offrande de Construction')),
                ('communication', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Communiqué')),
                ('temoignages_du_jour', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Témoignage')),
                ('cantiques_speciaux', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Cantiques Spéciaux')),
                ('anniversaire', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Anniversaires')),
                ('consecration', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Consecrations')),
                ('remerciement', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Remerciements')),
                ('conducteurs_de_chant', models.CharField(blank=True, max_length=200)),
                ('status', models.BooleanField(blank=True, default=0)),
                ('status_admin', models.BooleanField(blank=True, default=0)),
                ('diacres', models.ManyToManyField(blank=True, related_name='Diacres', to='Gestion_menbres.menbres')),
                ('predicateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestion_menbres.menbres', verbose_name='Prédicateur')),
            ],
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_comm', models.CharField(max_length=255, verbose_name='Type de communication')),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('date_comm', models.DateField(verbose_name='Date')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_menbres.menbres')),
            ],
        ),
        migrations.CreateModel(
            name='Comite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonction', models.CharField(choices=[('Président', 'Président'), ('Vice-président', 'Vice-président'), ('Collecteur', 'Collecteur')], max_length=255, verbose_name='Fonction')),
                ('menbre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Gestion_menbres.menbres', verbose_name='Membre')),
                ('quartier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_menbres.quartier', verbose_name='Quartier')),
            ],
        ),
        migrations.CreateModel(
            name='Besoin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('materiel', models.TextField(verbose_name='Démande')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(verbose_name='Prix')),
                ('destinateur', models.CharField(max_length=255, verbose_name='Destinataire')),
                ('technicien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_menbres.technique', verbose_name='Téchnicien')),
            ],
        ),
        migrations.CreateModel(
            name='Administateur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('profession', models.CharField(max_length=255, verbose_name='Profession')),
                ('debut_mandat', models.DateField(verbose_name='Debut mandat')),
                ('fin_mandat', models.DateField(verbose_name='Fin mandat')),
                ('etat_mandat', models.CharField(choices=[('En cours', 'En cours'), ('Terminé', 'Terminé'), ('Annulé', 'Annulé'), ('Suspendu', 'Suspendu'), ('Autre', 'Autre')], max_length=255, verbose_name='Etat mandat')),
                ('id_menbre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_menbres.menbres', verbose_name='Menbre')),
            ],
        ),
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_activ', models.CharField(max_length=255, verbose_name="Type d'activité")),
                ('date_activ', models.DateField(verbose_name='Date')),
                ('place_activ', models.CharField(max_length=255, verbose_name='Place')),
                ('membres', models.ManyToManyField(related_name='Activite_membres', to='Gestion_menbres.menbres')),
            ],
        ),
    ]
