# Generated by Django 4.2.7 on 2024-08-05 12:53

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_menbres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JourSemaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi'), ('dimanche', 'Dimanche')], max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='evenement',
            name='autres',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='evenement',
            name='heure_even',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Heure'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='administateur',
            name='etat_mandat',
            field=models.CharField(choices=[('En cours', 'En cours'), ('Terminé', 'Terminé'), ('Annulé', 'Annulé'), ('Suspendu', 'Suspendu'), ('Autre', 'Autre')], max_length=255, verbose_name='Etat mandat'),
        ),
        migrations.AlterField(
            model_name='comite',
            name='fonction',
            field=models.CharField(choices=[('Président', 'Président'), ('Vice-président', 'Vice-président'), ('Collecteur', 'Collecteur')], max_length=255, verbose_name='Fonction'),
        ),
        migrations.AlterField(
            model_name='comite',
            name='menbre',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Gestion_menbres.menbres', verbose_name='Membre'),
        ),
        migrations.AlterField(
            model_name='comite',
            name='quartier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_menbres.quartier', verbose_name='Quartier'),
        ),
        migrations.AlterField(
            model_name='communication',
            name='contenu',
            field=models.TextField(verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='communication',
            name='date_comm',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='communication',
            name='type_comm',
            field=models.CharField(max_length=255, verbose_name='Type de communication'),
        ),
        migrations.AlterField(
            model_name='diacre',
            name='etat_mandat',
            field=models.CharField(choices=[('En cour', 'En cours'), ('Terminé', 'Terminé'), ('Annulé', 'Annulé'), ('Suspendu', 'Suspendu'), ('Autre', 'Autre')], max_length=255),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='membres',
            field=models.ManyToManyField(blank=True, related_name='Evenement_membres', to='Gestion_menbres.menbres'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='place_even',
            field=models.CharField(max_length=255, verbose_name='Lieu'),
        ),
        migrations.AlterField(
            model_name='fonction',
            name='nom',
            field=models.CharField(max_length=255, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='menbres',
            name='etat_civil',
            field=models.CharField(choices=[('Célibataire', 'Célibataire'), ('Marié(e)', 'Marié(e)'), ('Divorcé(e)', 'Divorcé(e)'), ('Veuf/Veuve', 'Veuf/Veuve')], max_length=255, verbose_name='Etat civil'),
        ),
        migrations.AlterField(
            model_name='menbres',
            name='genre',
            field=models.CharField(choices=[('Masculin', 'Masculin'), ('Féminin', 'Féminin')], max_length=255),
        ),
        migrations.AlterField(
            model_name='menbres',
            name='groupe_sanguin',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=255, verbose_name='Groupe sanguin'),
        ),
        migrations.AlterField(
            model_name='menbres',
            name='quartier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_menbres.quartier', verbose_name='Quartier'),
        ),
        migrations.AlterField(
            model_name='menbres',
            name='statut',
            field=models.CharField(choices=[('Actif', 'Actif'), ('Inactif', 'Inactif')], max_length=255, verbose_name='Statut'),
        ),
        migrations.CreateModel(
            name='Culte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('heure_debut', models.TimeField(verbose_name='Debut service')),
                ('heure_fin', models.TimeField(verbose_name='Fin service')),
                ('predicateur_visiteur', models.CharField(blank=True, max_length=100, null=True, verbose_name='Prédicateur visiteur')),
                ('nombre_membres', models.PositiveIntegerField(blank=True, default=0, verbose_name='Effectif Total')),
                ('nombre_offrandes', models.FloatField(blank=True, default=0.0, verbose_name='Offrande Régulier')),
                ('nombre_construction', models.FloatField(blank=True, default=0.0, verbose_name='Offrande de Construction')),
                ('communication', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Communiqué')),
                ('temoignages_du_jour', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Témoignage')),
                ('cantiques_speciaux', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Cantiques Spéciaux')),
                ('anniversaire', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Anniversaires')),
                ('consecration', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Consecrations')),
                ('remerciement', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Remerciements')),
                ('conducteurs_de_chant', models.CharField(blank=True, max_length=200)),
                ('status', models.BooleanField(blank=True, default=0)),
                ('status_admin', models.BooleanField(blank=True, default=0)),
                ('diacres', models.ManyToManyField(blank=True, related_name='Diacres', to='Gestion_menbres.menbres')),
                ('predicateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestion_menbres.menbres', verbose_name='Prédicateur')),
            ],
        ),
        migrations.AddField(
            model_name='garde',
            name='emploi_temps',
            field=models.ManyToManyField(to='Gestion_menbres.joursemaine', verbose_name='Emploi du temps'),
        ),
    ]
