# Generated by Django 5.0.4 on 2024-05-10 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_menbres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comite',
            name='fonction',
            field=models.CharField(choices=[('Président', 'Président'), ('Président', 'Vice-président'), ('Président', 'Collecteur')], max_length=255, verbose_name='Fonction'),
        ),
        migrations.AlterField(
            model_name='comite',
            name='menbre',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Gestion_menbres.menbres', verbose_name='Membre'),
        ),
        migrations.AlterField(
            model_name='comite',
            name='quartier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_menbres.quartier', verbose_name='Quartier'),
        ),
        migrations.AlterField(
            model_name='menbres',
            name='etat_civil',
            field=models.CharField(choices=[('C', 'Célibataire'), ('M', 'Marié(e)'), ('D', 'Divorcé(e)'), ('V', 'Veuf/Veuve')], max_length=255, verbose_name='Etat civil'),
        ),
        migrations.AlterField(
            model_name='menbres',
            name='groupe_sanguin',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=255, verbose_name='Groupe sanguin'),
        ),
        migrations.AlterField(
            model_name='menbres',
            name='quartier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_menbres.quartier', verbose_name='Quartier'),
        ),
        migrations.AlterField(
            model_name='menbres',
            name='statut',
            field=models.CharField(choices=[('A', 'Ancien'), ('N', 'Nouveau'), ('O', 'Autre')], max_length=255, verbose_name='Statut'),
        ),
    ]
