# Generated by Django 5.0.4 on 2024-05-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_menbres', '0002_alter_comite_fonction_alter_comite_menbre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comite',
            name='fonction',
            field=models.CharField(choices=[('Président', 'Président'), ('Vice-président', 'Vice-président'), ('Collecteur', 'Collecteur')], max_length=255, verbose_name='Fonction'),
        ),
    ]
