# Generated by Django 5.0.4 on 2024-05-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_menbres', '0003_alter_comite_fonction'),
    ]

    operations = [
        migrations.CreateModel(
            name='JourSemaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi'), ('dimanche', 'Dimanche')], max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='communication',
            name='contenu',
            field=models.TextField(verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='communication',
            name='date_comm',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='communication',
            name='type_comm',
            field=models.CharField(max_length=255, verbose_name='Type de communication'),
        ),
        migrations.AlterField(
            model_name='fonction',
            name='nom',
            field=models.CharField(max_length=255, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='garde',
            name='emploi_temps',
            field=models.ManyToManyField(to='Gestion_menbres.joursemaine', verbose_name='Emploi du temps'),
        ),
    ]
