# Generated by Django 4.2.7 on 2024-06-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_menbres', '0004_joursemaine_alter_communication_contenu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='heure_even',
            field=models.TimeField(default='14:30:20.123456', verbose_name='Heure'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='administateur',
            name='etat_mandat',
            field=models.CharField(choices=[('En cours', 'En cours'), ('Terminé', 'Terminé'), ('Annulé', 'Annulé'), ('Suspendu', 'Suspendu'), ('Autre', 'Autre')], max_length=255, verbose_name='Etat mandat'),
        ),
        migrations.AlterField(
            model_name='diacre',
            name='etat_mandat',
            field=models.CharField(choices=[('En cour', 'En cours'), ('Terminé', 'Terminé'), ('Annulé', 'Annulé'), ('Suspendu', 'Suspendu'), ('Autre', 'Autre')], max_length=255),
        ),
        migrations.AlterField(
            model_name='menbres',
            name='etat_civil',
            field=models.CharField(choices=[('Célibataire', 'Célibataire'), ('Marié(e)', 'Marié(e)'), ('Divorcé(e)', 'Divorcé(e)'), ('Veuf/Veuve', 'Veuf/Veuve')], max_length=255, verbose_name='Etat civil'),
        ),
        migrations.AlterField(
            model_name='menbres',
            name='genre',
            field=models.CharField(choices=[('Masculin', 'Masculin'), ('Féminin', 'Féminin')], max_length=255),
        ),
        migrations.AlterField(
            model_name='menbres',
            name='statut',
            field=models.CharField(choices=[('Actif', 'Actif'), ('Inactif', 'Inactif')], max_length=255, verbose_name='Statut'),
        ),
    ]
