# Generated by Django 4.2.7 on 2024-06-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_menbres', '0005_evenement_heure_even_alter_administateur_etat_mandat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='membres',
            field=models.ManyToManyField(blank=True, null=True, related_name='Evenement_membres', to='Gestion_menbres.menbres'),
        ),
    ]
