# Generated by Django 4.2.7 on 2024-06-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_menbres', '0006_alter_evenement_membres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='place_even',
            field=models.CharField(max_length=255, verbose_name='Lieu'),
        ),
    ]
