# Generated by Django 4.2.7 on 2024-07-24 13:45

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_menbres', '0007_alter_evenement_place_even'),
    ]

    operations = [
        migrations.CreateModel(
            name='Culte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('heure_debut', models.TimeField(verbose_name='Debut service')),
                ('heure_fin', models.TimeField(verbose_name='Fin service')),
                ('predicateur_visiteur', models.CharField(blank=True, max_length=100, null=True, verbose_name='Prédicateur visiteur')),
                ('nombre_membres', models.PositiveIntegerField(verbose_name='Effectif Total')),
                ('nombre_offrandes', models.PositiveIntegerField(verbose_name='Offrande Régulier')),
                ('nombre_dimes', models.PositiveIntegerField(verbose_name='Dïmes')),
                ('nombre_construction', models.PositiveIntegerField(verbose_name='Offrande de Construction')),
                ('communication', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Communiqué')),
                ('temoignages_du_jour', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Témoignage')),
                ('cantiques_speciaux', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Cantiques Spéciaux')),
                ('conducteurs_de_chant', models.CharField(max_length=200)),
                ('diacres', models.ManyToManyField(blank=True, null=True, related_name='Diacres', to='Gestion_menbres.menbres')),
                ('predicateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_menbres.menbres', verbose_name='Prédicateur')),
            ],
        ),
    ]
