# Generated by Django 4.2.7 on 2024-07-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_menbres', '0009_alter_culte_conducteurs_de_chant_alter_culte_diacres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culte',
            name='heure_fin',
            field=models.TimeField(verbose_name='Fin service'),
        ),
        migrations.AlterField(
            model_name='culte',
            name='nombre_construction',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Offrande de Construction'),
        ),
        migrations.AlterField(
            model_name='culte',
            name='nombre_dimes',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Dïmes'),
        ),
        migrations.AlterField(
            model_name='culte',
            name='nombre_membres',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Effectif Total'),
        ),
        migrations.AlterField(
            model_name='culte',
            name='nombre_offrandes',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Offrande Régulier'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='membres',
            field=models.ManyToManyField(blank=True, related_name='Evenement_membres', to='Gestion_menbres.menbres'),
        ),
    ]
