# Generated by Django 4.2.7 on 2024-07-25 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_menbres', '0010_alter_culte_heure_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culte',
            name='predicateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestion_menbres.menbres', verbose_name='Prédicateur'),
        ),
    ]
