# Generated by Django 4.2.7 on 2024-07-26 11:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_menbres', '0011_alter_culte_predicateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='culte',
            name='anniversaire',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Anniversaires'),
        ),
        migrations.AddField(
            model_name='culte',
            name='consecration',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Consecrations'),
        ),
        migrations.AddField(
            model_name='culte',
            name='remerciement',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Remerciements'),
        ),
    ]
