# Generated by Django 4.2.7 on 2024-07-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_menbres', '0012_culte_anniversaire_culte_consecration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='culte',
            name='status',
            field=models.BooleanField(blank=True, default=0),
        ),
    ]
