# Generated by Django 4.2.7 on 2024-07-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_menbres', '0013_culte_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='autres',
            field=models.TextField(blank=True),
        ),
    ]
