# Generated by Django 4.2.7 on 2024-07-29 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_menbres', '0014_evenement_autres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='culte',
            name='nombre_dimes',
        ),
    ]
